include arlib/Makefile-head

PROGRAM = elbow
ARTYPE = exe
ARGUI = 0
ARGAME = 0
AROPENGL = 0
ARTHREAD = 0
ARWUTF = 0
ARSOCKET = 0
ARSOCKET_SSL = openssl
ARSOCKET_SSL_WINDOWS = schannel
ARTERMINAL = 1

include arlib/Makefile
